//! Host function implementations for the Wasm Component Model imports.
//!
//! Each WIT import interface maps to a trait generated by `wasmtime::component::bindgen!`.
//! With `trappable_imports: true`, all methods return `wasmtime::Result<T>`.

use crate::bindings::privstack::plugin::*;
use crate::permissions::Permission;
use crate::sandbox::PluginState;
use privstack_model::Entity;
use tracing::{debug, error, info, warn};

// types::Host is an empty marker trait generated by wasmtime bindgen
impl types::Host for PluginState {}

// ============================================================
// sdk::Host — Core CRUD operations (Tier 1, always granted)
// ============================================================

impl sdk::Host for PluginState {
    fn send(&mut self, message: types::SdkMessage) -> wasmtime::Result<types::SdkResponse> {
        let entity_type = &message.entity_type;

        if !self.declared_entity_types.contains(entity_type) {
            warn!(
                plugin_id = %self.plugin_id,
                entity_type = %entity_type,
                "Entity type access denied"
            );
            return Ok(types::SdkResponse {
                success: false,
                error_code: Some(403),
                error_message: Some(format!(
                    "plugin '{}' has not declared entity type '{}'",
                    self.plugin_id, entity_type
                )),
                data: None,
            });
        }

        debug!(
            plugin_id = %self.plugin_id,
            action = ?message.action,
            entity_type = %entity_type,
            "SDK send"
        );

        Ok(match message.action {
            types::SdkAction::Create => self.handle_create(entity_type, message.payload.as_deref()),
            types::SdkAction::Read => self.handle_read(message.entity_id.as_deref()),
            types::SdkAction::Update => self.handle_update(
                entity_type,
                message.entity_id.as_deref(),
                message.payload.as_deref(),
            ),
            types::SdkAction::Delete => self.handle_delete(message.entity_id.as_deref()),
            types::SdkAction::ListAll => self.handle_list(entity_type),
            types::SdkAction::Query => self.handle_query(
                entity_type,
                message.payload.as_deref(),
                &message.parameters,
            ),
            types::SdkAction::Trash => self.handle_trash(message.entity_id.as_deref()),
            types::SdkAction::Restore => self.handle_restore(message.entity_id.as_deref()),
            types::SdkAction::Link => self.handle_link(
                entity_type,
                message.entity_id.as_deref(),
                message.payload.as_deref(),
            ),
            types::SdkAction::Unlink => self.handle_unlink(
                entity_type,
                message.entity_id.as_deref(),
                message.payload.as_deref(),
            ),
            types::SdkAction::GetLinks => self.handle_get_links(
                entity_type,
                message.entity_id.as_deref(),
            ),
            _ => types::SdkResponse {
                success: false,
                error_code: Some(501),
                error_message: Some(format!("action {:?} not yet implemented", message.action)),
                data: None,
            },
        })
    }

    fn search(
        &mut self,
        query: String,
        entity_types: Option<Vec<String>>,
        limit: u32,
    ) -> wasmtime::Result<types::SdkResponse> {
        if let Some(ref types_filter) = entity_types {
            for et in types_filter {
                if !self.declared_entity_types.contains(et) {
                    return Ok(types::SdkResponse {
                        success: false,
                        error_code: Some(403),
                        error_message: Some(format!(
                            "plugin '{}' cannot search entity type '{}'",
                            self.plugin_id, et
                        )),
                        data: None,
                    });
                }
            }
        }

        let types_refs: Option<Vec<&str>> = entity_types
            .as_ref()
            .map(|v| v.iter().map(|s| s.as_str()).collect());

        Ok(match self
            .entity_store
            .search(&query, types_refs.as_deref(), limit as usize)
        {
            Ok(results) => {
                let json = serde_json::to_string(&results).unwrap_or_else(|_| "[]".into());
                types::SdkResponse {
                    success: true,
                    error_code: None,
                    error_message: None,
                    data: Some(json),
                }
            }
            Err(e) => types::SdkResponse {
                success: false,
                error_code: Some(500),
                error_message: Some(e.to_string()),
                data: None,
            },
        })
    }
}

impl PluginState {
    fn handle_create(&self, entity_type: &str, payload: Option<&str>) -> types::SdkResponse {
        let payload = match payload {
            Some(p) => p,
            None => {
                return types::SdkResponse {
                    success: false,
                    error_code: Some(400),
                    error_message: Some("create requires payload".into()),
                    data: None,
                }
            }
        };

        let data: serde_json::Value = match serde_json::from_str(payload) {
            Ok(v) => v,
            Err(e) => {
                return types::SdkResponse {
                    success: false,
                    error_code: Some(400),
                    error_message: Some(format!("invalid JSON payload: {}", e)),
                    data: None,
                }
            }
        };

        let now = chrono::Utc::now().timestamp();
        let id = uuid::Uuid::new_v4().to_string();
        let entity = Entity {
            id: id.clone(),
            entity_type: entity_type.to_string(),
            data,
            created_at: now,
            modified_at: now,
            created_by: self.plugin_id.clone(),
        };

        match self.entity_store.save_entity_raw(&entity) {
            Ok(()) => {
                let result = serde_json::json!({ "id": id });
                types::SdkResponse {
                    success: true,
                    error_code: None,
                    error_message: None,
                    data: Some(result.to_string()),
                }
            }
            Err(e) => types::SdkResponse {
                success: false,
                error_code: Some(500),
                error_message: Some(e.to_string()),
                data: None,
            },
        }
    }

    fn handle_read(&self, entity_id: Option<&str>) -> types::SdkResponse {
        let id = match entity_id {
            Some(id) => id,
            None => {
                return types::SdkResponse {
                    success: false,
                    error_code: Some(400),
                    error_message: Some("read requires entity_id".into()),
                    data: None,
                }
            }
        };

        match self.entity_store.get_entity(id) {
            Ok(Some(entity)) => {
                let json = serde_json::to_string(&entity).unwrap_or_else(|_| "{}".into());
                types::SdkResponse {
                    success: true,
                    error_code: None,
                    error_message: None,
                    data: Some(json),
                }
            }
            Ok(None) => types::SdkResponse {
                success: false,
                error_code: Some(404),
                error_message: Some("not found".into()),
                data: None,
            },
            Err(e) => types::SdkResponse {
                success: false,
                error_code: Some(500),
                error_message: Some(e.to_string()),
                data: None,
            },
        }
    }

    fn handle_update(
        &self,
        entity_type: &str,
        entity_id: Option<&str>,
        payload: Option<&str>,
    ) -> types::SdkResponse {
        let id = match entity_id {
            Some(id) => id,
            None => {
                return types::SdkResponse {
                    success: false,
                    error_code: Some(400),
                    error_message: Some("update requires entity_id".into()),
                    data: None,
                }
            }
        };
        let payload = match payload {
            Some(p) => p,
            None => {
                return types::SdkResponse {
                    success: false,
                    error_code: Some(400),
                    error_message: Some("update requires payload".into()),
                    data: None,
                }
            }
        };

        let data: serde_json::Value = match serde_json::from_str(payload) {
            Ok(v) => v,
            Err(e) => {
                return types::SdkResponse {
                    success: false,
                    error_code: Some(400),
                    error_message: Some(format!("invalid JSON payload: {}", e)),
                    data: None,
                }
            }
        };

        let now = chrono::Utc::now().timestamp();

        // Merge update payload into existing entity to preserve unchanged fields
        let entity = match self.entity_store.get_entity(id) {
            Ok(Some(mut existing)) => {
                match (existing.data.as_object_mut(), data) {
                    (Some(base), serde_json::Value::Object(updates)) => {
                        for (k, v) in updates {
                            base.insert(k, v);
                        }
                    }
                    (_, replacement) => {
                        existing.data = replacement;
                    }
                }
                existing.modified_at = now;
                existing
            }
            _ => {
                // Entity doesn't exist — create new (backwards-compatible)
                Entity {
                    id: id.to_string(),
                    entity_type: entity_type.to_string(),
                    data,
                    created_at: now,
                    modified_at: now,
                    created_by: self.plugin_id.clone(),
                }
            }
        };

        match self.entity_store.save_entity_raw(&entity) {
            Ok(()) => types::SdkResponse {
                success: true,
                error_code: None,
                error_message: None,
                data: None,
            },
            Err(e) => types::SdkResponse {
                success: false,
                error_code: Some(500),
                error_message: Some(e.to_string()),
                data: None,
            },
        }
    }

    fn handle_delete(&self, entity_id: Option<&str>) -> types::SdkResponse {
        let id = match entity_id {
            Some(id) => id,
            None => {
                return types::SdkResponse {
                    success: false,
                    error_code: Some(400),
                    error_message: Some("delete requires entity_id".into()),
                    data: None,
                }
            }
        };

        match self.entity_store.delete_entity(id) {
            Ok(()) => types::SdkResponse {
                success: true,
                error_code: None,
                error_message: None,
                data: None,
            },
            Err(e) => types::SdkResponse {
                success: false,
                error_code: Some(500),
                error_message: Some(e.to_string()),
                data: None,
            },
        }
    }

    fn handle_list(&self, entity_type: &str) -> types::SdkResponse {
        match self
            .entity_store
            .list_entities(entity_type, false, Some(500), None)
        {
            Ok(entities) => {
                let json = serde_json::to_string(&entities).unwrap_or_else(|_| "[]".into());
                types::SdkResponse {
                    success: true,
                    error_code: None,
                    error_message: None,
                    data: Some(json),
                }
            }
            Err(e) => types::SdkResponse {
                success: false,
                error_code: Some(500),
                error_message: Some(e.to_string()),
                data: None,
            },
        }
    }

    fn handle_query(
        &self,
        entity_type: &str,
        _payload: Option<&str>,
        parameters: &[(String, String)],
    ) -> types::SdkResponse {
        let limit = parameters
            .iter()
            .find(|(k, _)| k == "limit")
            .and_then(|(_, v)| v.parse::<usize>().ok())
            .unwrap_or(100);

        let filters: Vec<(String, serde_json::Value)> = parameters
            .iter()
            .filter(|(k, _)| k != "limit")
            .map(|(k, v)| (k.clone(), serde_json::Value::String(v.clone())))
            .collect();

        match self
            .entity_store
            .query_entities(entity_type, &filters, false, Some(limit))
        {
            Ok(entities) => {
                let json = serde_json::to_string(&entities).unwrap_or_else(|_| "[]".into());
                types::SdkResponse {
                    success: true,
                    error_code: None,
                    error_message: None,
                    data: Some(json),
                }
            }
            Err(e) => types::SdkResponse {
                success: false,
                error_code: Some(500),
                error_message: Some(e.to_string()),
                data: None,
            },
        }
    }

    fn handle_trash(&self, entity_id: Option<&str>) -> types::SdkResponse {
        let id = match entity_id {
            Some(id) => id,
            None => {
                return types::SdkResponse {
                    success: false,
                    error_code: Some(400),
                    error_message: Some("trash requires entity_id".into()),
                    data: None,
                }
            }
        };
        match self.entity_store.trash_entity(id) {
            Ok(()) => types::SdkResponse {
                success: true,
                error_code: None,
                error_message: None,
                data: None,
            },
            Err(e) => types::SdkResponse {
                success: false,
                error_code: Some(500),
                error_message: Some(e.to_string()),
                data: None,
            },
        }
    }

    fn handle_restore(&self, entity_id: Option<&str>) -> types::SdkResponse {
        let id = match entity_id {
            Some(id) => id,
            None => {
                return types::SdkResponse {
                    success: false,
                    error_code: Some(400),
                    error_message: Some("restore requires entity_id".into()),
                    data: None,
                }
            }
        };
        match self.entity_store.restore_entity(id) {
            Ok(()) => types::SdkResponse {
                success: true,
                error_code: None,
                error_message: None,
                data: None,
            },
            Err(e) => types::SdkResponse {
                success: false,
                error_code: Some(500),
                error_message: Some(e.to_string()),
                data: None,
            },
        }
    }

    /// Create a link between the source entity (entity_id) and a target specified in the payload.
    /// Payload JSON: `{ "target_type": "note", "target_id": "123", "link_type": "parent" }`
    fn handle_link(
        &self,
        source_type: &str,
        entity_id: Option<&str>,
        payload: Option<&str>,
    ) -> types::SdkResponse {
        let source_id = match entity_id {
            Some(id) => id,
            None => {
                return types::SdkResponse {
                    success: false,
                    error_code: Some(400),
                    error_message: Some("link requires entity_id (source)".into()),
                    data: None,
                }
            }
        };
        let payload = match payload {
            Some(p) => p,
            None => {
                return types::SdkResponse {
                    success: false,
                    error_code: Some(400),
                    error_message: Some("link requires payload with target_type and target_id".into()),
                    data: None,
                }
            }
        };
        let parsed: serde_json::Value = match serde_json::from_str(payload) {
            Ok(v) => v,
            Err(e) => {
                return types::SdkResponse {
                    success: false,
                    error_code: Some(400),
                    error_message: Some(format!("invalid JSON payload: {}", e)),
                    data: None,
                }
            }
        };
        let target_type = parsed
            .get("target_type")
            .and_then(|v| v.as_str())
            .unwrap_or(source_type);
        let target_id = match parsed.get("target_id").and_then(|v| v.as_str()) {
            Some(id) => id,
            None => {
                return types::SdkResponse {
                    success: false,
                    error_code: Some(400),
                    error_message: Some("payload must contain target_id".into()),
                    data: None,
                }
            }
        };

        debug!(
            plugin_id = %self.plugin_id,
            source_type, source_id, target_type, target_id,
            "Creating entity link"
        );

        match self
            .entity_store
            .save_link(source_type, source_id, target_type, target_id)
        {
            Ok(()) => types::SdkResponse {
                success: true,
                error_code: None,
                error_message: None,
                data: None,
            },
            Err(e) => types::SdkResponse {
                success: false,
                error_code: Some(500),
                error_message: Some(e.to_string()),
                data: None,
            },
        }
    }

    /// Remove a link between the source entity (entity_id) and a target specified in the payload.
    fn handle_unlink(
        &self,
        source_type: &str,
        entity_id: Option<&str>,
        payload: Option<&str>,
    ) -> types::SdkResponse {
        let source_id = match entity_id {
            Some(id) => id,
            None => {
                return types::SdkResponse {
                    success: false,
                    error_code: Some(400),
                    error_message: Some("unlink requires entity_id (source)".into()),
                    data: None,
                }
            }
        };
        let payload = match payload {
            Some(p) => p,
            None => {
                return types::SdkResponse {
                    success: false,
                    error_code: Some(400),
                    error_message: Some("unlink requires payload with target_type and target_id".into()),
                    data: None,
                }
            }
        };
        let parsed: serde_json::Value = match serde_json::from_str(payload) {
            Ok(v) => v,
            Err(e) => {
                return types::SdkResponse {
                    success: false,
                    error_code: Some(400),
                    error_message: Some(format!("invalid JSON payload: {}", e)),
                    data: None,
                }
            }
        };
        let target_type = parsed
            .get("target_type")
            .and_then(|v| v.as_str())
            .unwrap_or(source_type);
        let target_id = match parsed.get("target_id").and_then(|v| v.as_str()) {
            Some(id) => id,
            None => {
                return types::SdkResponse {
                    success: false,
                    error_code: Some(400),
                    error_message: Some("payload must contain target_id".into()),
                    data: None,
                }
            }
        };

        debug!(
            plugin_id = %self.plugin_id,
            source_type, source_id, target_type, target_id,
            "Removing entity link"
        );

        match self
            .entity_store
            .remove_link(source_type, source_id, target_type, target_id)
        {
            Ok(()) => types::SdkResponse {
                success: true,
                error_code: None,
                error_message: None,
                data: None,
            },
            Err(e) => types::SdkResponse {
                success: false,
                error_code: Some(500),
                error_message: Some(e.to_string()),
                data: None,
            },
        }
    }

    /// Get all links for an entity (both outgoing and incoming).
    /// Returns a JSON array of link objects with source/target info and titles.
    fn handle_get_links(
        &self,
        entity_type: &str,
        entity_id: Option<&str>,
    ) -> types::SdkResponse {
        let id = match entity_id {
            Some(id) => id,
            None => {
                return types::SdkResponse {
                    success: false,
                    error_code: Some(400),
                    error_message: Some("get-links requires entity_id".into()),
                    data: None,
                }
            }
        };

        // Collect outgoing + incoming links
        let mut links: Vec<serde_json::Value> = Vec::new();

        // Outgoing: source is this entity
        if let Ok(outgoing) = self.entity_store.get_links_from(entity_type, id) {
            for (target_type, target_id) in outgoing {
                let entity = self.entity_store.get_entity(&target_id).ok().flatten();
                let title = entity
                    .as_ref()
                    .and_then(|e| e.data.get("title").and_then(|v| v.as_str()).map(|s| s.to_string()))
                    .unwrap_or_else(|| "Untitled".to_string());
                let icon = entity
                    .as_ref()
                    .and_then(|e| e.data.get("icon").and_then(|v| v.as_str()).map(|s| s.to_string()));

                links.push(serde_json::json!({
                    "source_id": id,
                    "source_type": entity_type,
                    "target_id": target_id,
                    "target_type": target_type,
                    "target_title": title,
                    "link_type": target_type,
                    "icon": icon,
                    "direction": "outgoing",
                }));
            }
        }

        // Incoming: target is this entity
        if let Ok(incoming) = self.entity_store.get_links_to(entity_type, id) {
            for (source_type, source_id) in incoming {
                let entity = self.entity_store.get_entity(&source_id).ok().flatten();
                let title = entity
                    .as_ref()
                    .and_then(|e| e.data.get("title").and_then(|v| v.as_str()).map(|s| s.to_string()))
                    .unwrap_or_else(|| "Untitled".to_string());
                let icon = entity
                    .as_ref()
                    .and_then(|e| e.data.get("icon").and_then(|v| v.as_str()).map(|s| s.to_string()));

                links.push(serde_json::json!({
                    "source_id": source_id,
                    "source_type": source_type,
                    "target_id": id,
                    "target_type": entity_type,
                    "source_title": title,
                    "link_type": source_type,
                    "icon": icon,
                    "direction": "incoming",
                }));
            }
        }

        let json = serde_json::to_string(&links).unwrap_or_else(|_| "[]".into());
        types::SdkResponse {
            success: true,
            error_code: None,
            error_message: None,
            data: Some(json),
        }
    }
}

// ============================================================
// settings::Host — Plugin-scoped key-value settings (Tier 1)
// ============================================================

impl settings::Host for PluginState {
    fn get(&mut self, key: String, default_value: String) -> wasmtime::Result<String> {
        Ok(self
            .settings
            .get(&key)
            .cloned()
            .unwrap_or(default_value))
    }

    fn set(&mut self, key: String, value: String) -> wasmtime::Result<()> {
        self.settings.insert(key, value);
        Ok(())
    }

    fn remove(&mut self, key: String) -> wasmtime::Result<()> {
        self.settings.remove(&key);
        Ok(())
    }
}

// ============================================================
// logger::Host — Structured logging with plugin context (Tier 1)
// ============================================================

impl logger::Host for PluginState {
    fn debug(&mut self, message: String) -> wasmtime::Result<()> {
        debug!(plugin_id = %self.plugin_id, "{}", message);
        Ok(())
    }

    fn info(&mut self, message: String) -> wasmtime::Result<()> {
        info!(plugin_id = %self.plugin_id, "{}", message);
        Ok(())
    }

    fn warn(&mut self, message: String) -> wasmtime::Result<()> {
        warn!(plugin_id = %self.plugin_id, "{}", message);
        Ok(())
    }

    fn error(&mut self, message: String) -> wasmtime::Result<()> {
        error!(plugin_id = %self.plugin_id, "{}", message);
        Ok(())
    }
}

// ============================================================
// navigation::Host — Plugin navigation (Tier 1)
// ============================================================

impl navigation::Host for PluginState {
    fn navigate_to(&mut self, plugin_id: String) -> wasmtime::Result<()> {
        debug!(
            plugin_id = %self.plugin_id,
            target = %plugin_id,
            "Navigate to plugin"
        );
        self.pending_navigation = Some(plugin_id);
        Ok(())
    }

    fn navigate_back(&mut self) -> wasmtime::Result<()> {
        debug!(plugin_id = %self.plugin_id, "Navigate back");
        self.pending_navigation = Some("__back__".into());
        Ok(())
    }
}

// ============================================================
// state-notify::Host — View state change notification (Tier 1)
// ============================================================

impl state_notify::Host for PluginState {
    fn notify_state_changed(&mut self, _json_patch: Option<String>) -> wasmtime::Result<()> {
        self.state_dirty = true;
        Ok(())
    }
}

// ============================================================
// vault::Host — Encrypted vault operations (Tier 2, JIT prompted)
// ============================================================

impl vault::Host for PluginState {
    fn is_initialized(&mut self, _vault_id: String) -> wasmtime::Result<bool> {
        if self.check_permission(Permission::Vault).is_err() {
            return Ok(false);
        }
        Ok(false)
    }

    fn initialize(&mut self, _vault_id: String, _password: String) -> wasmtime::Result<()> {
        if let Err(e) = self.check_permission(Permission::Vault) {
            warn!(plugin_id = %self.plugin_id, "Vault access denied: {}", e);
        }
        Ok(())
    }

    fn unlock(&mut self, _vault_id: String, _password: String) -> wasmtime::Result<()> {
        if let Err(e) = self.check_permission(Permission::Vault) {
            warn!(plugin_id = %self.plugin_id, "Vault access denied: {}", e);
        }
        Ok(())
    }

    fn lock(&mut self, _vault_id: String) -> wasmtime::Result<()> {
        if let Err(e) = self.check_permission(Permission::Vault) {
            warn!(plugin_id = %self.plugin_id, "Vault access denied: {}", e);
        }
        Ok(())
    }

    fn blob_store(
        &mut self,
        _vault_id: String,
        _blob_id: String,
        _data: Vec<u8>,
    ) -> wasmtime::Result<()> {
        if let Err(e) = self.check_permission(Permission::Vault) {
            warn!(plugin_id = %self.plugin_id, "Vault access denied: {}", e);
        }
        Ok(())
    }

    fn blob_read(
        &mut self,
        _vault_id: String,
        _blob_id: String,
    ) -> wasmtime::Result<Vec<u8>> {
        if self.check_permission(Permission::Vault).is_err() {
            return Ok(Vec::new());
        }
        Ok(Vec::new())
    }

    fn blob_delete(&mut self, _vault_id: String, _blob_id: String) -> wasmtime::Result<()> {
        if let Err(e) = self.check_permission(Permission::Vault) {
            warn!(plugin_id = %self.plugin_id, "Vault access denied: {}", e);
        }
        Ok(())
    }
}

// ============================================================
// linking::Host — Cross-plugin item linking (Tier 2, JIT prompted)
// ============================================================

impl linking::Host for PluginState {
    fn search_items(
        &mut self,
        _query: String,
        _max_results: u32,
    ) -> wasmtime::Result<Vec<types::LinkableItem>> {
        if self.check_permission(Permission::Linking).is_err() {
            return Ok(Vec::new());
        }
        Ok(Vec::new())
    }

    fn get_item_by_id(
        &mut self,
        _item_id: String,
    ) -> wasmtime::Result<Option<types::LinkableItem>> {
        if self.check_permission(Permission::Linking).is_err() {
            return Ok(None);
        }
        Ok(None)
    }

    fn get_all_providers(&mut self) -> wasmtime::Result<Vec<types::LinkProviderInfo>> {
        if self.check_permission(Permission::Linking).is_err() {
            return Ok(Vec::new());
        }
        Ok(Vec::new())
    }

    fn query_all(
        &mut self,
        _query: String,
        _max_results: u32,
    ) -> wasmtime::Result<Vec<types::LinkableItem>> {
        if self.check_permission(Permission::Linking).is_err() {
            return Ok(Vec::new());
        }
        Ok(Vec::new())
    }
}

// ============================================================
// dialogs::Host — Dialog prompts (Tier 2, JIT prompted)
// ============================================================

impl dialogs::Host for PluginState {
    fn show_confirmation(
        &mut self,
        _title: String,
        _message: String,
    ) -> wasmtime::Result<bool> {
        if self.check_permission(Permission::Dialogs).is_err() {
            return Ok(false);
        }
        Ok(false)
    }

    fn show_open_file(
        &mut self,
        _title: String,
        _filters: Vec<String>,
    ) -> wasmtime::Result<Option<String>> {
        if self.check_permission(Permission::Dialogs).is_err() {
            return Ok(None);
        }
        Ok(None)
    }
}

// ============================================================
// network::Host — HTTP fetch (Tier 3, install-time permission)
// ============================================================

impl network::Host for PluginState {
    fn fetch_url(
        &mut self,
        url: String,
        method: String,
        headers: Vec<network::HttpHeader>,
        body: Option<Vec<u8>>,
    ) -> wasmtime::Result<Result<network::HttpResponse, String>> {
        if let Err(e) = self.check_permission(Permission::Network) {
            return Ok(Err(format!("network permission denied: {}", e)));
        }

        debug!(
            plugin_id = %self.plugin_id,
            url = %url,
            method = %method,
            "Network fetch"
        );

        let client = match reqwest::blocking::Client::builder()
            .timeout(std::time::Duration::from_secs(30))
            .user_agent("PrivStack/1.0")
            .build()
        {
            Ok(c) => c,
            Err(e) => return Ok(Err(format!("failed to create HTTP client: {}", e))),
        };

        let method = match method.parse::<reqwest::Method>() {
            Ok(m) => m,
            Err(e) => return Ok(Err(format!("invalid HTTP method: {}", e))),
        };

        let mut request = client.request(method, &url);

        for header in &headers {
            request = request.header(&header.name, &header.value);
        }

        if let Some(body_bytes) = body {
            request = request.body(body_bytes);
        }

        let response = match request.send() {
            Ok(r) => r,
            Err(e) => return Ok(Err(format!("HTTP request failed: {}", e))),
        };

        let status = response.status().as_u16();
        let resp_headers: Vec<network::HttpHeader> = response
            .headers()
            .iter()
            .map(|(name, value)| network::HttpHeader {
                name: name.to_string(),
                value: value.to_str().unwrap_or("").to_string(),
            })
            .collect();

        let body_bytes = match response.bytes() {
            Ok(b) => b.to_vec(),
            Err(e) => return Ok(Err(format!("failed to read response body: {}", e))),
        };

        Ok(Ok(network::HttpResponse {
            status,
            headers: resp_headers,
            body: body_bytes,
        }))
    }
}

